r4916 -Fixed vFACTORcutEDGESx: now it is used directly in the relevant row for momentum on the matrix for coupled momentum-continuity. Used for TYPEfreeSLIP 0,1 AND 2. Added also UfromCENTERactiveTOcenterFULL for going back to center of the total edge -Modified projects to allow 64 bit compilation (some conflicts are created since this error appears: Error 1 fatal error C1905 Front end and back end not compatible (must target same processor) ). -Added correction of dh/dx for non-orthogonality  through SourceU and cutfac (gives instability, neglected for now) -DOUBLEuvh: not working. -Checked momentum output for cutcells. Working properly. -Added analytical integration of polygon: analyticalPOLY -IMPORTANT: AUMENTED MAX NUMBER OF VARIABLES TO BE PRINTED IN FILE NEFIS: #define MAX_CEL_DIM  200 /* increased to 200*/